### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by Sm1tShah** [mugdha-gupta/ShopAuth#13]
Link to the in-progress draft:
https://docs.google.com/document/d/1L6BcoXMdlMkLv8_36Y6IG-TMfW3lHCOAlHB_bDZQ96Q/edit

We need to submit proposal on March 1 in class with signatures of all teammates and Dr Cole and Gene too.

So we should have a target to finish this by 22nd to show to Dr Cole in the meeting on 22nd.

- [ ] Finish the document before 22nd

- [ ] Dr Cole's Signature on 22nd or before

- [ ] Gene Woten's Signature before 1st March

- [ ] Submit one soft copy online

- [ ] Bring signed hard copy to turn in in class on March 1

Guideline on how to do it from Elearning:
[Proposal-guideline.docx](https://github.com/mugdha-gupta/ShopAuth/files/2849526/Proposal-guideline.docx)

**Comment by CryHavoc21** [comment]
Project report has been signed and turned in.
