### ISSUE TITLE
Develop API

### ISSUE THREAD

**Issue by miamiheat710** [mugdha-gupta/ShopAuth#15]
- [x] Develop API

- [x] Test out Backend(Java) connectivity to DB(mySQL server locally hosted)

**Comment by miamiheat710** [comment]
https://docs.google.com/document/d/1v9ilNPHv0ehc44d7n0PtOJPrkZullwnBexG8zIUbN6E/edit?usp=sharing

**Comment by miamiheat710** [comment]
https://www.javatpoint.com/example-to-connect-to-the-mysql-database

**Comment by Sm1tShah** [comment]
Chris and I were able to use the above tutorial to have java code that connects to the localhost mySQL server and query it

**Comment by miamiheat710** [comment]
Switched to springboot and got user CRUD calls finished and manually tested

**Comment by CryHavoc21** [comment]
dude wtf it's like 3am

**Comment by miamiheat710** [comment]
Might need this for log controller https://www.baeldung.com/rest-api-pagination-in-spring

**Comment by miamiheat710** [comment]
Very good example of foreign keys in spring boot https://www.callicoder.com/hibernate-spring-boot-jpa-one-to-many-mapping-example/

**Comment by miamiheat710** [comment]
#17

**Comment by miamiheat710** [comment]
#19
