### ISSUE TITLE
Design the database (recon)

### ISSUE THREAD

**Issue by mugdha-gupta** [mugdha-gupta/ShopAuth#3]
- [x] Figure out what is involved in this

- [x] brief the team

**Comment by CryHavoc21** [comment]
So I did a bit of digging, and MySQL has integrations for Python and Java, and I've used the ones for Java (JDBC). If we end up using Java for server software and python on the pi, we have the ability to use MySQL as our database.

**Comment by mugdha-gupta** [comment]
@CryHavoc21 that's good to hear. Another questions for the team in general is what goes into designing a database? I don't have much expertise but would like to be involved in how it happens so I can see the process :)

**Comment by Sm1tShah** [comment]
We pretty much figured out the database design when we met in ecsw yesterday. I'd say this issue can be marked as finished. Only need to make sure we have a good way to show Dr Cole our design

**Comment by miamiheat710** [comment]
We decided to go server side with the database and use api calls

**Comment by nymishaj** [comment]
Google Doc of the database design:
https://docs.google.com/document/d/1IL7J8sZ_gJxaRHAThxhs4XLJ1ew5cSsclwPSGqlLA8I/edit?usp=sharing
